apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    email: {{ .Values.email }}
    {{- with .Values.issuer }}
    server: {{ .server }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key
      name: {{ .secretName }}
    {{- end }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingress.name }}