apiVersion: v1
kind: Service
metadata:
  {{- $app := .Values.app -}}
  {{- $protocol := .Values.protocol -}}
  {{- $httpPort := .Values.httpPort -}}
  {{- $grpcPort := .Values.grpcPort -}}
  {{- $httpName := .Values.httpName -}}
  {{- $grpcName := .Values.grpcName -}}
  {{- with .Values.service }}
  name: {{ .name }}
spec:
  selector:
    app: {{ $app }}
  ports:
    - protocol: {{ $protocol }}
      port: {{ $httpPort }}
      targetPort: {{ $httpName }}
      name: {{ .httpName }}
    - protocol: {{ $protocol }}
      port: {{ $grpcPort }}
      targetPort: {{ $grpcName }}
      name: {{ .grpcName }}
  type: {{ .type }}
  {{- end }}